# Generated by Django 4.2.7 on 2023-12-10 15:28
# Generated by Django 4.2.7 on 2023-12-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDb',
            fields=[
                ('empl_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('birth_date', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True)),
                ('contact_info', models.TextField(blank=True, db_column='contact info', null=True)),
                ('myunknowncolumn', models.TextField(blank=True, db_column='MyUnknownColumn', null=True)),
                ('myunknowncolumn_0_field', models.TextField(blank=True, db_column='MyUnknownColumn_[0]', null=True)),
                ('degree', models.TextField(blank=True, null=True)),
                ('reg_no', models.TextField(blank=True, null=True)),
                ('acc_no', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, db_column='Salary', null=True)),
                ('contr_date', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('status_color', models.TextField(blank=True, null=True)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('risk_point', models.TextField(blank=True, null=True)),
                ('risk_field', models.TextField(blank=True, db_column='risk%', null=True)),
            ],
            options={
                'db_table': 'status_db',
                'managed': False,
            },
        ),
    ]
