# Generated by Django 4.2.7 on 2023-12-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedb',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='statusdb',
            options={'managed': True},
        ),
    ]
